
spring:
  application:
    name: naming-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


#---REF ---#

#https://dzone.com/articles/the-mystery-of-eurekas-self-preservation