server:
  port: 8081

spring:
  application:
    name: context-server

eureka:
  instance:
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/
