server:
  port: 8092

spring:
  application:
    name: context-server
  cloud:
    config:
      uri: http://localhost:8888
      name: development
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/
