server:
  port: 8093

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: admin-service