server:
  port: 8762

spring:
  application:
    name: edge-server
  cloud:
    config:
      uri: http://localhost:8888
      name: development
  main:
    allow-bean-definition-overriding: true


eureka:
  instance:
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/

zuul:
  strip-prefix: false
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      serviceId: AUTH-SERVICE
      stripPrefix: false
      sensitiveHeaders:
    admin-service:
      path: /admin/**
      serviceId: ADMIN-SERVICE
      sensitiveHeader: Cookie
    cogent-server:
      path: /**
      serviceId: COGENT-SERVER



