server:
  port: 8762

spring:
  application:
    name: edge-server
  cloud:
    config:
      uri: http://localhost:8888
      name: development
  main:
    allow-bean-definition-overriding: true


eureka:
  instance:
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/

zuul:
  strip-prefix: false
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      serviceId: AUTH-SERVICE
      stripPrefix: false
      sensitiveHeaders:

    admin-service:
      path: /admin/**
      serviceId: ADMIN-SERVICE
    cogent-server:
      path: /**
      serviceId: COGENT-SERVER

    pharmacy-server:
      path: /pharmacy/**
      serviceId: PHARMACY-SERVICE

    hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds:  15000
            timeout:
              enabled: false

  ribbon:
    PoolMaxThreads: 500
    MaxTotalConnections: 500
    MaxConnectionsPerHost: 50
    ReadTimeout: 2000
    ConnectTimeout: 2000
    MaxHttpConnectionsPerHost: 50
    MaxTotalHttpConnections: 500
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0


    ribbon:
      ConnectTimeout: 10000
      ReadTimeout: 10000



