server:
  port: 8762

spring:
  application:
    name: edge-server
  cloud:
    config:
      uri: http://localhost:8888
      name: development
  main:
    allow-bean-definition-overriding: true


eureka:
  instance:
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

zuul:
  strip-prefix: false
  ignored-services: '*'
  host:
    connect-timeout-millis: 60000 # starting the connection
    socket-timeout-millis: 60000  # monitor the continuous incoming data flow
  routes:
    hystrix:
      command:
        default:
          execution:
            isolation:
              thread:
                timeoutInMilliseconds: 160000


    ribbon:
      eureka:
        enabled: true
      ReadTimeout: 80000
      ConnectTimeout: 80000
      MaxTotalHttpConnections: 500
      MaxConnectionsPerHost: 100

    auth-service:
      path: /auth/**
      serviceId: AUTH-SERVICE
      stripPrefix: false
      sensitiveHeaders:

    admin-service:
      path: /admin/**
      serviceId: ADMIN-SERVICE
      ribbon:
        ReadTimeout: 80000
        ConnectTimeout: 80000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100


    cogent-server:
      path: /**
      serviceId: COGENT-SERVER

    pharmacy-server:
      path: /pharmacy/**
      serviceId: PHARMACY-SERVICE

    email-server:
      path:  /email-server/**
      serviceId: EMAIL-SERVER
      ribbon:
        ReadTimeout: 80000
        ConnectTimeout: 80000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100
