server:
  port: 8762

spring:
  application:
    name: edge-server
  cloud:
    config:
      uri: http://localhost:8888
      name: development
  main:
    allow-bean-definition-overriding: true


eureka:
  instance:
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/

zuul:
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
    admin-service:
      path: /admin/**
      service-id: admin-service
    cogent-server:
      path: /**
      service-id: cogent-server
