server:
  port: 8888

spring:
  application:
    name: config-server
  config:
    name: config-server

  profiles:
    include: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/
