server:
  port: 8085

spring:
  application:
    name: email-server

  cloud:
    config:
      uri: http://localhost:8888
      name: development

eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
    secure-port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.secure-port}/eureka/

